//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 11.0.50727.1
// 
namespace Benner_Engage.PagamentosService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Request", Namespace="http://schemas.datacontract.org/2004/07/Benner.Tecnologia.Common.EnterpriseServic" +
        "eLibrary")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Benner_Engage.PagamentosService.LogoutRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Benner_Engage.PagamentosService.PrimeiroPeriodoComSaldoFeriasRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Benner_Engage.PagamentosService.SimularFeriasRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Benner_Engage.PagamentosService.SimularRescisaoRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Benner_Engage.PagamentosService.ObterFuncionariosRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Benner_Engage.PagamentosService.LoginRequest))]
    public partial class Request : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string AuthenticationTokenIdField;
        
        private Benner_Engage.PagamentosService.ServiceVersion VersionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthenticationTokenId {
            get {
                return this.AuthenticationTokenIdField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthenticationTokenIdField, value) != true)) {
                    this.AuthenticationTokenIdField = value;
                    this.RaisePropertyChanged("AuthenticationTokenId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Benner_Engage.PagamentosService.ServiceVersion Version {
            get {
                return this.VersionField;
            }
            set {
                if ((object.ReferenceEquals(this.VersionField, value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceVersion", Namespace="http://schemas.datacontract.org/2004/07/Benner.Tecnologia.Common.EnterpriseServic" +
        "eLibrary")]
    public partial class ServiceVersion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int MajorField;
        
        private int MinorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Major {
            get {
                return this.MajorField;
            }
            set {
                if ((this.MajorField.Equals(value) != true)) {
                    this.MajorField = value;
                    this.RaisePropertyChanged("Major");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Minor {
            get {
                return this.MinorField;
            }
            set {
                if ((this.MinorField.Equals(value) != true)) {
                    this.MinorField = value;
                    this.RaisePropertyChanged("Minor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogoutRequest", Namespace="http://schemas.datacontract.org/2004/07/Benner.Tecnologia.EnterpriseServiceLibrar" +
        "y")]
    public partial class LogoutRequest : Benner_Engage.PagamentosService.Request {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PrimeiroPeriodoComSaldoFeriasRequest", Namespace="http://schemas.datacontract.org/2004/07/Benner.RH.Pagamentos.DataContracts")]
    public partial class PrimeiroPeriodoComSaldoFeriasRequest : Benner_Engage.PagamentosService.Request {
        
        private long FuncionarioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Funcionario {
            get {
                return this.FuncionarioField;
            }
            set {
                if ((this.FuncionarioField.Equals(value) != true)) {
                    this.FuncionarioField = value;
                    this.RaisePropertyChanged("Funcionario");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SimularFeriasRequest", Namespace="http://schemas.datacontract.org/2004/07/Benner.RH.Pagamentos.DataContracts")]
    public partial class SimularFeriasRequest : Benner_Engage.PagamentosService.Request {
        
        private long FuncionarioField;
        
        private System.Nullable<System.DateTime> InicioField;
        
        private System.Nullable<System.DateTime> DataPagamentoField;
        
        private System.Nullable<int> CalcularFeriasField;
        
        private System.Nullable<int> PeriodoAbonoField;
        
        private decimal DiasFeriasField;
        
        private System.Nullable<decimal> DiasAbonoField;
        
        private System.Nullable<decimal> DiasFeriasAmpliadasField;
        
        private System.Nullable<decimal> Perc13SalarioField;
        
        private System.Nullable<bool> PrevisaoDescontosField;
        
        private System.Nullable<bool> PagarLiquidoField;
        
        private System.Nullable<bool> PagarMultaField;
        
        private System.Nullable<bool> EmprestimoFeriasField;
        
        private System.Nullable<System.DateTime> DataEmprestimoField;
        
        private System.Nullable<System.DateTime> InicioDescontoField;
        
        private System.Nullable<int> ParcelasField;
        
        private System.Nullable<bool> PrevisaoINSSOutrasEmpresasField;
        
        private System.Nullable<bool> EmitirRelatorioResultadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Funcionario {
            get {
                return this.FuncionarioField;
            }
            set {
                if ((this.FuncionarioField.Equals(value) != true)) {
                    this.FuncionarioField = value;
                    this.RaisePropertyChanged("Funcionario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Inicio {
            get {
                return this.InicioField;
            }
            set {
                if ((this.InicioField.Equals(value) != true)) {
                    this.InicioField = value;
                    this.RaisePropertyChanged("Inicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Nullable<System.DateTime> DataPagamento {
            get {
                return this.DataPagamentoField;
            }
            set {
                if ((this.DataPagamentoField.Equals(value) != true)) {
                    this.DataPagamentoField = value;
                    this.RaisePropertyChanged("DataPagamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<int> CalcularFerias {
            get {
                return this.CalcularFeriasField;
            }
            set {
                if ((this.CalcularFeriasField.Equals(value) != true)) {
                    this.CalcularFeriasField = value;
                    this.RaisePropertyChanged("CalcularFerias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<int> PeriodoAbono {
            get {
                return this.PeriodoAbonoField;
            }
            set {
                if ((this.PeriodoAbonoField.Equals(value) != true)) {
                    this.PeriodoAbonoField = value;
                    this.RaisePropertyChanged("PeriodoAbono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public decimal DiasFerias {
            get {
                return this.DiasFeriasField;
            }
            set {
                if ((this.DiasFeriasField.Equals(value) != true)) {
                    this.DiasFeriasField = value;
                    this.RaisePropertyChanged("DiasFerias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.Nullable<decimal> DiasAbono {
            get {
                return this.DiasAbonoField;
            }
            set {
                if ((this.DiasAbonoField.Equals(value) != true)) {
                    this.DiasAbonoField = value;
                    this.RaisePropertyChanged("DiasAbono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public System.Nullable<decimal> DiasFeriasAmpliadas {
            get {
                return this.DiasFeriasAmpliadasField;
            }
            set {
                if ((this.DiasFeriasAmpliadasField.Equals(value) != true)) {
                    this.DiasFeriasAmpliadasField = value;
                    this.RaisePropertyChanged("DiasFeriasAmpliadas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public System.Nullable<decimal> Perc13Salario {
            get {
                return this.Perc13SalarioField;
            }
            set {
                if ((this.Perc13SalarioField.Equals(value) != true)) {
                    this.Perc13SalarioField = value;
                    this.RaisePropertyChanged("Perc13Salario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public System.Nullable<bool> PrevisaoDescontos {
            get {
                return this.PrevisaoDescontosField;
            }
            set {
                if ((this.PrevisaoDescontosField.Equals(value) != true)) {
                    this.PrevisaoDescontosField = value;
                    this.RaisePropertyChanged("PrevisaoDescontos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public System.Nullable<bool> PagarLiquido {
            get {
                return this.PagarLiquidoField;
            }
            set {
                if ((this.PagarLiquidoField.Equals(value) != true)) {
                    this.PagarLiquidoField = value;
                    this.RaisePropertyChanged("PagarLiquido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public System.Nullable<bool> PagarMulta {
            get {
                return this.PagarMultaField;
            }
            set {
                if ((this.PagarMultaField.Equals(value) != true)) {
                    this.PagarMultaField = value;
                    this.RaisePropertyChanged("PagarMulta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public System.Nullable<bool> EmprestimoFerias {
            get {
                return this.EmprestimoFeriasField;
            }
            set {
                if ((this.EmprestimoFeriasField.Equals(value) != true)) {
                    this.EmprestimoFeriasField = value;
                    this.RaisePropertyChanged("EmprestimoFerias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public System.Nullable<System.DateTime> DataEmprestimo {
            get {
                return this.DataEmprestimoField;
            }
            set {
                if ((this.DataEmprestimoField.Equals(value) != true)) {
                    this.DataEmprestimoField = value;
                    this.RaisePropertyChanged("DataEmprestimo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public System.Nullable<System.DateTime> InicioDesconto {
            get {
                return this.InicioDescontoField;
            }
            set {
                if ((this.InicioDescontoField.Equals(value) != true)) {
                    this.InicioDescontoField = value;
                    this.RaisePropertyChanged("InicioDesconto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public System.Nullable<int> Parcelas {
            get {
                return this.ParcelasField;
            }
            set {
                if ((this.ParcelasField.Equals(value) != true)) {
                    this.ParcelasField = value;
                    this.RaisePropertyChanged("Parcelas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public System.Nullable<bool> PrevisaoINSSOutrasEmpresas {
            get {
                return this.PrevisaoINSSOutrasEmpresasField;
            }
            set {
                if ((this.PrevisaoINSSOutrasEmpresasField.Equals(value) != true)) {
                    this.PrevisaoINSSOutrasEmpresasField = value;
                    this.RaisePropertyChanged("PrevisaoINSSOutrasEmpresas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public System.Nullable<bool> EmitirRelatorioResultado {
            get {
                return this.EmitirRelatorioResultadoField;
            }
            set {
                if ((this.EmitirRelatorioResultadoField.Equals(value) != true)) {
                    this.EmitirRelatorioResultadoField = value;
                    this.RaisePropertyChanged("EmitirRelatorioResultado");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SimularRescisaoRequest", Namespace="http://schemas.datacontract.org/2004/07/Benner.RH.Pagamentos.DataContracts")]
    public partial class SimularRescisaoRequest : Benner_Engage.PagamentosService.Request {
        
        private long FuncionarioField;
        
        private System.Nullable<System.DateTime> DemissaoDataField;
        
        private int CausaDemissaoField;
        
        private System.Nullable<int> AvisoPrevioTipoField;
        
        private System.Nullable<System.DateTime> AvisoPrevioInicioField;
        
        private System.Nullable<int> AvisoPrevioDiasField;
        
        private System.Nullable<bool> EmitirRelatorioResultadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Funcionario {
            get {
                return this.FuncionarioField;
            }
            set {
                if ((this.FuncionarioField.Equals(value) != true)) {
                    this.FuncionarioField = value;
                    this.RaisePropertyChanged("Funcionario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.Nullable<System.DateTime> DemissaoData {
            get {
                return this.DemissaoDataField;
            }
            set {
                if ((this.DemissaoDataField.Equals(value) != true)) {
                    this.DemissaoDataField = value;
                    this.RaisePropertyChanged("DemissaoData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int CausaDemissao {
            get {
                return this.CausaDemissaoField;
            }
            set {
                if ((this.CausaDemissaoField.Equals(value) != true)) {
                    this.CausaDemissaoField = value;
                    this.RaisePropertyChanged("CausaDemissao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<int> AvisoPrevioTipo {
            get {
                return this.AvisoPrevioTipoField;
            }
            set {
                if ((this.AvisoPrevioTipoField.Equals(value) != true)) {
                    this.AvisoPrevioTipoField = value;
                    this.RaisePropertyChanged("AvisoPrevioTipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<System.DateTime> AvisoPrevioInicio {
            get {
                return this.AvisoPrevioInicioField;
            }
            set {
                if ((this.AvisoPrevioInicioField.Equals(value) != true)) {
                    this.AvisoPrevioInicioField = value;
                    this.RaisePropertyChanged("AvisoPrevioInicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.Nullable<int> AvisoPrevioDias {
            get {
                return this.AvisoPrevioDiasField;
            }
            set {
                if ((this.AvisoPrevioDiasField.Equals(value) != true)) {
                    this.AvisoPrevioDiasField = value;
                    this.RaisePropertyChanged("AvisoPrevioDias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.Nullable<bool> EmitirRelatorioResultado {
            get {
                return this.EmitirRelatorioResultadoField;
            }
            set {
                if ((this.EmitirRelatorioResultadoField.Equals(value) != true)) {
                    this.EmitirRelatorioResultadoField = value;
                    this.RaisePropertyChanged("EmitirRelatorioResultado");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObterFuncionariosRequest", Namespace="http://schemas.datacontract.org/2004/07/Benner.RH.Pagamentos.DataContracts")]
    public partial class ObterFuncionariosRequest : Benner_Engage.PagamentosService.Request {
        
        private string UsuarioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginRequest", Namespace="http://schemas.datacontract.org/2004/07/Benner.Tecnologia.EnterpriseServiceLibrar" +
        "y")]
    public partial class LoginRequest : Benner_Engage.PagamentosService.Request {
        
        private string UserNameField;
        
        private string PasswordField;
        
        private long CompanyHandleField;
        
        private long BranchHandleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long CompanyHandle {
            get {
                return this.CompanyHandleField;
            }
            set {
                if ((this.CompanyHandleField.Equals(value) != true)) {
                    this.CompanyHandleField = value;
                    this.RaisePropertyChanged("CompanyHandle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long BranchHandle {
            get {
                return this.BranchHandleField;
            }
            set {
                if ((this.BranchHandleField.Equals(value) != true)) {
                    this.BranchHandleField = value;
                    this.RaisePropertyChanged("BranchHandle");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://schemas.datacontract.org/2004/07/Benner.Tecnologia.Common.EnterpriseServic" +
        "eLibrary")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Benner_Engage.PagamentosService.LogoutResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Benner_Engage.PagamentosService.PrimeiroPeriodoComSaldoFeriasResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Benner_Engage.PagamentosService.SimularFeriasResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Benner_Engage.PagamentosService.SimularRescisaoResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Benner_Engage.PagamentosService.ObterFuncionariosResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Benner_Engage.PagamentosService.LoginResponse))]
    public partial class Response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string AuthenticationTokenIdField;
        
        private Benner_Engage.PagamentosService.ServiceVersion VersionField;
        
        private string MessageField;
        
        private bool FailureField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthenticationTokenId {
            get {
                return this.AuthenticationTokenIdField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthenticationTokenIdField, value) != true)) {
                    this.AuthenticationTokenIdField = value;
                    this.RaisePropertyChanged("AuthenticationTokenId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Benner_Engage.PagamentosService.ServiceVersion Version {
            get {
                return this.VersionField;
            }
            set {
                if ((object.ReferenceEquals(this.VersionField, value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool Failure {
            get {
                return this.FailureField;
            }
            set {
                if ((this.FailureField.Equals(value) != true)) {
                    this.FailureField = value;
                    this.RaisePropertyChanged("Failure");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogoutResponse", Namespace="http://schemas.datacontract.org/2004/07/Benner.Tecnologia.EnterpriseServiceLibrar" +
        "y")]
    public partial class LogoutResponse : Benner_Engage.PagamentosService.Response {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PrimeiroPeriodoComSaldoFeriasResponse", Namespace="http://schemas.datacontract.org/2004/07/Benner.RH.Pagamentos.DataContracts")]
    public partial class PrimeiroPeriodoComSaldoFeriasResponse : Benner_Engage.PagamentosService.Response {
        
        private System.DateTime PeriodoAdquiridoInicioField;
        
        private System.DateTime PeriodoAdquiridoFimField;
        
        private System.DateTime PeriodoConcessivoInicioField;
        
        private System.DateTime PeriodoConcessivoFimField;
        
        private int DiasAfastamentoField;
        
        private long HandleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PeriodoAdquiridoInicio {
            get {
                return this.PeriodoAdquiridoInicioField;
            }
            set {
                if ((this.PeriodoAdquiridoInicioField.Equals(value) != true)) {
                    this.PeriodoAdquiridoInicioField = value;
                    this.RaisePropertyChanged("PeriodoAdquiridoInicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime PeriodoAdquiridoFim {
            get {
                return this.PeriodoAdquiridoFimField;
            }
            set {
                if ((this.PeriodoAdquiridoFimField.Equals(value) != true)) {
                    this.PeriodoAdquiridoFimField = value;
                    this.RaisePropertyChanged("PeriodoAdquiridoFim");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime PeriodoConcessivoInicio {
            get {
                return this.PeriodoConcessivoInicioField;
            }
            set {
                if ((this.PeriodoConcessivoInicioField.Equals(value) != true)) {
                    this.PeriodoConcessivoInicioField = value;
                    this.RaisePropertyChanged("PeriodoConcessivoInicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime PeriodoConcessivoFim {
            get {
                return this.PeriodoConcessivoFimField;
            }
            set {
                if ((this.PeriodoConcessivoFimField.Equals(value) != true)) {
                    this.PeriodoConcessivoFimField = value;
                    this.RaisePropertyChanged("PeriodoConcessivoFim");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int DiasAfastamento {
            get {
                return this.DiasAfastamentoField;
            }
            set {
                if ((this.DiasAfastamentoField.Equals(value) != true)) {
                    this.DiasAfastamentoField = value;
                    this.RaisePropertyChanged("DiasAfastamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public long Handle {
            get {
                return this.HandleField;
            }
            set {
                if ((this.HandleField.Equals(value) != true)) {
                    this.HandleField = value;
                    this.RaisePropertyChanged("Handle");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SimularFeriasResponse", Namespace="http://schemas.datacontract.org/2004/07/Benner.RH.Pagamentos.DataContracts")]
    public partial class SimularFeriasResponse : Benner_Engage.PagamentosService.Response {
        
        private System.Nullable<long> FolhaFuncionarioField;
        
        private System.Collections.ObjectModel.ObservableCollection<Benner_Engage.PagamentosService.FolhaVerba> FolhaVerbasField;
        
        private string InconsistenciasField;
        
        private string OcorrenciasCalculoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> FolhaFuncionario {
            get {
                return this.FolhaFuncionarioField;
            }
            set {
                if ((this.FolhaFuncionarioField.Equals(value) != true)) {
                    this.FolhaFuncionarioField = value;
                    this.RaisePropertyChanged("FolhaFuncionario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<Benner_Engage.PagamentosService.FolhaVerba> FolhaVerbas {
            get {
                return this.FolhaVerbasField;
            }
            set {
                if ((object.ReferenceEquals(this.FolhaVerbasField, value) != true)) {
                    this.FolhaVerbasField = value;
                    this.RaisePropertyChanged("FolhaVerbas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Inconsistencias {
            get {
                return this.InconsistenciasField;
            }
            set {
                if ((object.ReferenceEquals(this.InconsistenciasField, value) != true)) {
                    this.InconsistenciasField = value;
                    this.RaisePropertyChanged("Inconsistencias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OcorrenciasCalculo {
            get {
                return this.OcorrenciasCalculoField;
            }
            set {
                if ((object.ReferenceEquals(this.OcorrenciasCalculoField, value) != true)) {
                    this.OcorrenciasCalculoField = value;
                    this.RaisePropertyChanged("OcorrenciasCalculo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SimularRescisaoResponse", Namespace="http://schemas.datacontract.org/2004/07/Benner.RH.Pagamentos.DataContracts")]
    public partial class SimularRescisaoResponse : Benner_Engage.PagamentosService.Response {
        
        private System.Nullable<long> FolhaFuncionarioField;
        
        private System.Collections.ObjectModel.ObservableCollection<Benner_Engage.PagamentosService.FolhaVerba> FolhaVerbasField;
        
        private string InconsistenciasField;
        
        private string OcorrenciasCalculoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> FolhaFuncionario {
            get {
                return this.FolhaFuncionarioField;
            }
            set {
                if ((this.FolhaFuncionarioField.Equals(value) != true)) {
                    this.FolhaFuncionarioField = value;
                    this.RaisePropertyChanged("FolhaFuncionario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<Benner_Engage.PagamentosService.FolhaVerba> FolhaVerbas {
            get {
                return this.FolhaVerbasField;
            }
            set {
                if ((object.ReferenceEquals(this.FolhaVerbasField, value) != true)) {
                    this.FolhaVerbasField = value;
                    this.RaisePropertyChanged("FolhaVerbas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Inconsistencias {
            get {
                return this.InconsistenciasField;
            }
            set {
                if ((object.ReferenceEquals(this.InconsistenciasField, value) != true)) {
                    this.InconsistenciasField = value;
                    this.RaisePropertyChanged("Inconsistencias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OcorrenciasCalculo {
            get {
                return this.OcorrenciasCalculoField;
            }
            set {
                if ((object.ReferenceEquals(this.OcorrenciasCalculoField, value) != true)) {
                    this.OcorrenciasCalculoField = value;
                    this.RaisePropertyChanged("OcorrenciasCalculo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObterFuncionariosResponse", Namespace="http://schemas.datacontract.org/2004/07/Benner.RH.Pagamentos.DataContracts")]
    public partial class ObterFuncionariosResponse : Benner_Engage.PagamentosService.Response {
        
        private System.Collections.ObjectModel.ObservableCollection<Benner_Engage.PagamentosService.DadosFuncionarios> FuncionariosField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<Benner_Engage.PagamentosService.DadosFuncionarios> Funcionarios {
            get {
                return this.FuncionariosField;
            }
            set {
                if ((object.ReferenceEquals(this.FuncionariosField, value) != true)) {
                    this.FuncionariosField = value;
                    this.RaisePropertyChanged("Funcionarios");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginResponse", Namespace="http://schemas.datacontract.org/2004/07/Benner.Tecnologia.EnterpriseServiceLibrar" +
        "y")]
    public partial class LoginResponse : Benner_Engage.PagamentosService.Response {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FolhaVerba", Namespace="http://schemas.datacontract.org/2004/07/Benner.RH.Pagamentos.DataContracts")]
    public partial class FolhaVerba : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int CodigoVerbaField;
        
        private System.Nullable<decimal> HorasField;
        
        private string NomeVerbaField;
        
        private System.Nullable<decimal> SalarioHoraField;
        
        private char TipoVerbaField;
        
        private System.Nullable<decimal> ValorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoVerba {
            get {
                return this.CodigoVerbaField;
            }
            set {
                if ((this.CodigoVerbaField.Equals(value) != true)) {
                    this.CodigoVerbaField = value;
                    this.RaisePropertyChanged("CodigoVerba");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Horas {
            get {
                return this.HorasField;
            }
            set {
                if ((this.HorasField.Equals(value) != true)) {
                    this.HorasField = value;
                    this.RaisePropertyChanged("Horas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeVerba {
            get {
                return this.NomeVerbaField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeVerbaField, value) != true)) {
                    this.NomeVerbaField = value;
                    this.RaisePropertyChanged("NomeVerba");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> SalarioHora {
            get {
                return this.SalarioHoraField;
            }
            set {
                if ((this.SalarioHoraField.Equals(value) != true)) {
                    this.SalarioHoraField = value;
                    this.RaisePropertyChanged("SalarioHora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char TipoVerba {
            get {
                return this.TipoVerbaField;
            }
            set {
                if ((this.TipoVerbaField.Equals(value) != true)) {
                    this.TipoVerbaField = value;
                    this.RaisePropertyChanged("TipoVerba");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((this.ValorField.Equals(value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DadosFuncionarios", Namespace="http://schemas.datacontract.org/2004/07/Benner.RH.Pagamentos.DataContracts")]
    public partial class DadosFuncionarios : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime DataAdmissaoField;
        
        private System.DateTime DataNascimentoField;
        
        private byte[] FotoField;
        
        private string HandleField;
        
        private string NomeField;
        
        private string SalarioAtualField;
        
        private string TipoColaboradorField;
        
        private string TipoSanguineoField;
        
        private string ViajaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataAdmissao {
            get {
                return this.DataAdmissaoField;
            }
            set {
                if ((this.DataAdmissaoField.Equals(value) != true)) {
                    this.DataAdmissaoField = value;
                    this.RaisePropertyChanged("DataAdmissao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataNascimento {
            get {
                return this.DataNascimentoField;
            }
            set {
                if ((this.DataNascimentoField.Equals(value) != true)) {
                    this.DataNascimentoField = value;
                    this.RaisePropertyChanged("DataNascimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Foto {
            get {
                return this.FotoField;
            }
            set {
                if ((object.ReferenceEquals(this.FotoField, value) != true)) {
                    this.FotoField = value;
                    this.RaisePropertyChanged("Foto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Handle {
            get {
                return this.HandleField;
            }
            set {
                if ((object.ReferenceEquals(this.HandleField, value) != true)) {
                    this.HandleField = value;
                    this.RaisePropertyChanged("Handle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SalarioAtual {
            get {
                return this.SalarioAtualField;
            }
            set {
                if ((object.ReferenceEquals(this.SalarioAtualField, value) != true)) {
                    this.SalarioAtualField = value;
                    this.RaisePropertyChanged("SalarioAtual");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoColaborador {
            get {
                return this.TipoColaboradorField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoColaboradorField, value) != true)) {
                    this.TipoColaboradorField = value;
                    this.RaisePropertyChanged("TipoColaborador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoSanguineo {
            get {
                return this.TipoSanguineoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoSanguineoField, value) != true)) {
                    this.TipoSanguineoField = value;
                    this.RaisePropertyChanged("TipoSanguineo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Viaja {
            get {
                return this.ViajaField;
            }
            set {
                if ((object.ReferenceEquals(this.ViajaField, value) != true)) {
                    this.ViajaField = value;
                    this.RaisePropertyChanged("Viaja");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Benner.Tecnologia.EnterpriseServiceLibrar" +
        "y")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Benner_Engage.PagamentosService.SecurityServiceFault))]
    public partial class ServiceFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SecurityServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Benner.Tecnologia.EnterpriseServiceLibrar" +
        "y")]
    public partial class SecurityServiceFault : Benner_Engage.PagamentosService.ServiceFault {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PagamentosService.IPagamentosService")]
    public interface IPagamentosService {
        
        [System.ServiceModel.OperationContractAttribute(Action="Login", ReplyAction="http://tempuri.org/IAuthentication/LoginResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Benner_Engage.PagamentosService.SecurityServiceFault), Action="http://tempuri.org/IAuthentication/LoginSecurityServiceFaultFault", Name="SecurityServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Benner.Tecnologia.EnterpriseServiceLibrar" +
            "y")]
        System.Threading.Tasks.Task<Benner_Engage.PagamentosService.LoginResponse> LoginAsync(Benner_Engage.PagamentosService.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Logout", ReplyAction="http://tempuri.org/IAuthentication/LogoutResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Benner_Engage.PagamentosService.SecurityServiceFault), Action="http://tempuri.org/IAuthentication/LogoutSecurityServiceFaultFault", Name="SecurityServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Benner.Tecnologia.EnterpriseServiceLibrar" +
            "y")]
        System.Threading.Tasks.Task<Benner_Engage.PagamentosService.LogoutResponse> LogoutAsync(Benner_Engage.PagamentosService.LogoutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagamentosService/PrimeiroPeriodoComSaldoFerias", ReplyAction="http://tempuri.org/IPagamentosService/PrimeiroPeriodoComSaldoFeriasResponse")]
        System.Threading.Tasks.Task<Benner_Engage.PagamentosService.PrimeiroPeriodoComSaldoFeriasResponse> PrimeiroPeriodoComSaldoFeriasAsync(Benner_Engage.PagamentosService.PrimeiroPeriodoComSaldoFeriasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagamentosService/SimularFerias", ReplyAction="http://tempuri.org/IPagamentosService/SimularFeriasResponse")]
        System.Threading.Tasks.Task<Benner_Engage.PagamentosService.SimularFeriasResponse> SimularFeriasAsync(Benner_Engage.PagamentosService.SimularFeriasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagamentosService/SimularRescisao", ReplyAction="http://tempuri.org/IPagamentosService/SimularRescisaoResponse")]
        System.Threading.Tasks.Task<Benner_Engage.PagamentosService.SimularRescisaoResponse> SimularRescisaoAsync(Benner_Engage.PagamentosService.SimularRescisaoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagamentosService/ObterFuncionarios", ReplyAction="http://tempuri.org/IPagamentosService/ObterFuncionariosResponse")]
        System.Threading.Tasks.Task<Benner_Engage.PagamentosService.ObterFuncionariosResponse> ObterFuncionariosAsync(Benner_Engage.PagamentosService.ObterFuncionariosRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPagamentosServiceChannel : Benner_Engage.PagamentosService.IPagamentosService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PagamentosServiceClient : System.ServiceModel.ClientBase<Benner_Engage.PagamentosService.IPagamentosService>, Benner_Engage.PagamentosService.IPagamentosService {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PagamentosServiceClient() : 
                base(PagamentosServiceClient.GetDefaultBinding(), PagamentosServiceClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IPagamentosService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PagamentosServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(PagamentosServiceClient.GetBindingForEndpoint(endpointConfiguration), PagamentosServiceClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PagamentosServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PagamentosServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PagamentosServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PagamentosServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PagamentosServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Threading.Tasks.Task<Benner_Engage.PagamentosService.LoginResponse> LoginAsync(Benner_Engage.PagamentosService.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<Benner_Engage.PagamentosService.LogoutResponse> LogoutAsync(Benner_Engage.PagamentosService.LogoutRequest request) {
            return base.Channel.LogoutAsync(request);
        }
        
        public System.Threading.Tasks.Task<Benner_Engage.PagamentosService.PrimeiroPeriodoComSaldoFeriasResponse> PrimeiroPeriodoComSaldoFeriasAsync(Benner_Engage.PagamentosService.PrimeiroPeriodoComSaldoFeriasRequest request) {
            return base.Channel.PrimeiroPeriodoComSaldoFeriasAsync(request);
        }
        
        public System.Threading.Tasks.Task<Benner_Engage.PagamentosService.SimularFeriasResponse> SimularFeriasAsync(Benner_Engage.PagamentosService.SimularFeriasRequest request) {
            return base.Channel.SimularFeriasAsync(request);
        }
        
        public System.Threading.Tasks.Task<Benner_Engage.PagamentosService.SimularRescisaoResponse> SimularRescisaoAsync(Benner_Engage.PagamentosService.SimularRescisaoRequest request) {
            return base.Channel.SimularRescisaoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Benner_Engage.PagamentosService.ObterFuncionariosResponse> ObterFuncionariosAsync(Benner_Engage.PagamentosService.ObterFuncionariosRequest request) {
            return base.Channel.ObterFuncionariosAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPagamentosService)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPagamentosService)) {
                return new System.ServiceModel.EndpointAddress("http://testeengage/Engage/app_services/PagamentosService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return PagamentosServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IPagamentosService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return PagamentosServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IPagamentosService);
        }
        
        public enum EndpointConfiguration {
            
            BasicHttpBinding_IPagamentosService,
        }

    }
}
